/**
 * Types for the AI-driven research planner.
 *
 * The research planner generates a personalized set of search queries based on
 * the user's full context (goal, balances, cards, spending, transfer catalog,
 * and temporal position). It replaces hardcoded query templates with
 * AI-reasoned queries that adapt to each user's situation.
 */

/**
 * The category of information a research query seeks.
 * - flight: flight award redemption options
 * - hotel: hotel award redemption options
 * - card: credit card offers (welcome bonuses, spending multipliers)
 * - temporal: time-sensitive information (booking windows, promotions, devaluations)
 * - value: sweet spots, transfer bonuses, disproportionately good redemptions
 */
export type ResearchQueryCategory =
  | "flight"
  | "hotel"
  | "card"
  | "temporal"
  | "value";

/**
 * A single search query generated by the research planner.
 */
export interface ResearchPlanQuery {
  /** The search string to send to the search provider. */
  query: string;
  /** Trusted domains to restrict the search to. Must be a subset of TRUSTED_DOMAINS. */
  includeDomains: string[];
  /** Why this query exists — what information gap it fills. */
  purpose: string;
  /** What category of information this query seeks. */
  category: ResearchQueryCategory;
  /** Search depth preference. Defaults to "basic" when absent. */
  searchDepth?: "basic" | "advanced";
}

/**
 * The complete research plan generated by the AI research planner.
 */
export interface ResearchPlan {
  /** The set of queries to execute. Maximum 8. */
  queries: ResearchPlanQuery[];
  /** The planner's reasoning about what information gaps exist and how the queries address them. */
  reasoning: string;
  /** ISO timestamp of when the plan was generated. */
  generatedAt: string;
}

/**
 * A reward program reference for planner input.
 */
export interface PlannerRewardProgram {
  /** Compatibility placeholder; never an internal identifier. */
  id: string;
  name: string;
}

/**
 * A reward account (sanitized) for planner input.
 * Contains a public program name and balance but no database identifiers.
 */
export interface PlannerRewardAccount {
  programName: string | null;
  balance: number;
  ownerType: "self" | "companion";
  verificationStatus: "unverified" | "verified";
}

/**
 * A wallet card (sanitized) for planner input.
 */
export interface PlannerWalletCard {
  name: string;
  issuer: string;
  rewardCurrency: string;
}

/**
 * A spending category aggregate for planner input.
 */
export interface PlannerSpendingCategory {
  category: string;
  monthlyAverage: number;
}

/**
 * A transfer partner relationship for planner input.
 * Tells the planner which programs the user's points can transfer to.
 */
export interface PlannerTransferPartner {
  sourceProgramName: string;
  partnerProgramName: string;
  partnerFamily: "airline_miles" | "hotel_points" | "other";
}

/**
 * The complete input to the research planner.
 * All fields are sanitized — no userId, database IDs, ownerKey, ownerLabel,
 * balanceAsOf, or goal.status.
 */
export interface ResearchPlannerInput {
  /** The user's goal (sanitized subset). */
  goal: {
    type: "travel";
    title: string;
    origin: string[];
    destinations: string[];
    earliestDeparture: string | null;
    latestReturn: string | null;
    minimumNights: number | null;
    maximumNights: number | null;
    travelerCount: number;
    cabinPreference: string;
    optimizationPriority: string;
    maximumCashBudget: number | null;
    currency: string;
    allowNewCards: boolean;
  };
  /** Reward accounts the user owns (sanitized). */
  rewardAccounts: PlannerRewardAccount[];
  /** Wallet cards the user owns (sanitized). */
  walletCards: PlannerWalletCard[];
  /** Monthly spending by category (aggregated from purchases). */
  monthlySpendingByCategory: PlannerSpendingCategory[];
  /** Reward programs the user participates in. */
  customerRewardPrograms: PlannerRewardProgram[];
  /** Authoritative transfer-partner relationships, when available. */
  transferPartners: PlannerTransferPartner[];
  /** Current date (ISO string) for temporal reasoning. */
  currentDate: string;
  /** Days until earliest departure (null if no departure date). */
  daysUntilDeparture: number | null;
}

/**
 * Interface for research planner implementations.
 */
export interface ResearchPlanner {
  generateResearchPlan(input: ResearchPlannerInput): Promise<ResearchPlan>;
}
