"use client";

import { useId, useState } from "react";
import { AlertTriangle, ArrowRightLeft, Bed, HelpCircle, Lightbulb, Plane } from "lucide-react";
import type { CustomerSafeEstimate, CustomerSafeStrategyPresentation } from "@/lib/goals/customerSafeStrategyPresentation";

function points(value: number | null): string { return value === null ? "Amount not confirmed" : new Intl.NumberFormat("en-US").format(value); }
function Disclosure({ label, children }: { label: string; children: React.ReactNode }) {
  const [expanded, setExpanded] = useState(false);
  const panelId = useId();
  return <div className="rounded-xl border border-white/5 bg-white/[0.02] p-3">
    <button type="button" className="min-h-11 w-full text-left text-sm font-medium text-slate-200" aria-expanded={expanded} aria-controls={panelId} onClick={() => setExpanded((current) => !current)}>{label}</button>
    <div id={panelId} hidden={!expanded} className="mt-3">{children}</div>
  </div>;
}

function EstimateCard({ estimate }: { estimate: CustomerSafeEstimate }) {
  return <li className="rounded-xl border border-white/5 bg-white/[0.02] p-3"><div className="flex flex-wrap justify-between gap-2"><span className="text-sm font-medium text-white">{estimate.programName}</span><span className="text-sm font-semibold text-white">{points(estimate.pointsRequired)} points</span></div><p className="mt-1 text-xs text-slate-400">{estimate.redemptionLabel} · {estimate.pricingLabel} · {estimate.evidenceLabel}</p>{estimate.itineraryLabel ? <p className="mt-1 text-sm text-slate-300">{estimate.itineraryLabel}</p> : null}<p className="mt-1 text-xs text-slate-400">{estimate.availabilityLabel}{estimate.cashFees !== null ? ` · Fees: ${estimate.cashFees}` : ""}{estimate.seats !== null ? ` · Seats: ${estimate.seats}` : ""}</p><p className="mt-1 text-xs text-slate-500">{estimate.coverageLabel}{estimate.travelerCountCovered !== null ? ` · ${estimate.travelerCountCovered} travelers` : ""}{estimate.nightCountCovered !== null ? ` · ${estimate.nightCountCovered} nights` : ""}</p></li>;
}

export function CustomerSafeStrategyContent({ presentation }: { presentation: CustomerSafeStrategyPresentation }) {
  return <div className="mt-4 space-y-4">
    {presentation.flightPlanningEstimate ? <section aria-labelledby="flight-planning-estimate" className="rounded-xl border border-sky-400/20 bg-sky-400/5 p-3"><h3 id="flight-planning-estimate" className="text-sm font-medium text-sky-200">{presentation.flightPlanningEstimate.label}</h3><p className="mt-1 text-sm text-white">{presentation.flightPlanningEstimate.route} · {presentation.flightPlanningEstimate.dates}</p><p className="mt-1 text-sm text-white">{presentation.flightPlanningEstimate.priceLabel}</p><p className="mt-1 text-xs text-slate-400">{presentation.flightPlanningEstimate.travelersLabel} · {presentation.flightPlanningEstimate.cabin} · {presentation.flightPlanningEstimate.evidenceLabel}</p><p className="mt-1 text-xs text-slate-500">Retrieved {presentation.flightPlanningEstimate.retrievedAt}. {presentation.flightPlanningEstimate.verificationLabel}. {presentation.flightPlanningEstimate.availabilityLabel}.</p>{presentation.flightPlanningEstimate.segments.length > 0 ? <ul className="mt-2 space-y-1 text-xs text-slate-400">{presentation.flightPlanningEstimate.segments.map((item, index) => <li key={`planning-segment-${index}`}>{item}</li>)}</ul> : null}{presentation.flightPlanningEstimate.unknowns.length > 0 ? <p className="mt-2 text-xs text-amber-200">Unknown: {presentation.flightPlanningEstimate.unknowns.join(", ")}</p> : null}</section> : null}
    <section aria-labelledby="presentation-strategy"><h3 id="presentation-strategy" className="text-base font-semibold text-white">Your planning strategy</h3><div className="mt-2 flex flex-wrap gap-x-3 gap-y-1 text-xs text-slate-400"><span>Saved goal constraints</span><span>Planning estimates may not match every constraint. Check current details before acting.</span>{presentation.goal.nightsLabel ? <span>{presentation.goal.nightsLabel}</span> : null}{presentation.goal.budgetLabel ? <span>{presentation.goal.budgetLabel}</span> : null}<span>{presentation.goal.priority}</span></div><p className="mt-1 text-xs text-slate-500">Planning guidance based on your saved goal, not a booking recommendation.</p><h4 className="mt-2 text-base font-semibold text-white">{presentation.strategy.headline}</h4><p className="mt-2 text-sm leading-relaxed text-slate-300">{presentation.strategy.summary}</p></section>
    <section aria-labelledby="ways-to-make-it-work"><h3 id="ways-to-make-it-work" className="text-base font-semibold text-white">Ways to make it work</h3><p className="mt-1 text-sm text-slate-300">{presentation.rewards.summary}</p><Disclosure label="View reward account details"><div className="space-y-3">{presentation.rewards.verified.length > 0 ? <div><h4 className="text-xs font-medium uppercase tracking-wide text-emerald-300">Confirmed rewards</h4><ul className="mt-2 space-y-2">{presentation.rewards.verified.map((account) => <li key={account.key} className="rounded-xl border border-white/5 p-3"><p className="text-sm font-medium text-white">{account.programName}</p><p className="mt-1 text-sm text-white">{points(account.balance)} points</p><p className="mt-1 text-xs text-slate-400">{account.ownerLabel} · {account.verificationLabel} · Balance as of {account.balanceAsOf}</p></li>)}</ul></div> : null}{presentation.rewards.unverified.length > 0 ? <div><h4 className="text-xs font-medium uppercase tracking-wide text-amber-300">Balances needing confirmation</h4><ul className="mt-2 space-y-2">{presentation.rewards.unverified.map((account) => <li key={account.key} className="rounded-xl border border-white/5 p-3"><p className="text-sm font-medium text-white">{account.programName}</p><p className="mt-1 text-sm text-white">{points(account.balance)} points</p><p className="mt-1 text-xs text-slate-400">{account.ownerLabel} · {account.verificationLabel} · Balance as of {account.balanceAsOf}</p></li>)}</ul></div> : null}</div></Disclosure>{presentation.rewards.scenarios.length > 0 ? <Disclosure label={`View ${presentation.rewards.scenarios.length} planning paths`}><div className="space-y-3">{presentation.rewards.scenarios.map((scenario) => <article key={scenario.key} className="rounded-lg border border-white/5 p-3"><h4 className="text-sm font-medium text-white">{scenario.label}</h4><p className="mt-1 text-xs text-slate-400">{scenario.statusLabel}</p>{scenario.title ? <p className="mt-1 text-sm text-slate-300">{scenario.title}</p> : null}{scenario.flight ? <EstimateCard estimate={scenario.flight} /> : null}{scenario.hotel ? <EstimateCard estimate={scenario.hotel} /> : null}{scenario.allocations.length > 0 ? <ul className="mt-2 space-y-2">{scenario.allocations.map((allocation) => <li key={allocation.key} className="rounded-lg bg-white/[0.03] p-2 text-xs text-slate-300">{allocation.programName} · {allocation.ownerLabel} · {points(allocation.plannedPoints)} planned points · {points(allocation.pointsGap)} gap · {allocation.fundingLabel}</li>)}</ul> : null}</article>)}</div></Disclosure> : null}</section>
    {presentation.flightEstimates.length > 0 ? <section aria-labelledby="flight-estimates"><h3 id="flight-estimates" className="flex items-center gap-2 text-sm font-medium text-slate-200"><Plane className="h-4 w-4 text-sky-300" />Flight planning estimates</h3><ul className="mt-2 space-y-2">{presentation.flightEstimates.map((estimate) => <EstimateCard key={estimate.key} estimate={estimate} />)}</ul></section> : null}
    {presentation.hotelEstimates.length > 0 ? <section aria-labelledby="hotel-estimates"><h3 id="hotel-estimates" className="flex items-center gap-2 text-sm font-medium text-slate-200"><Bed className="h-4 w-4 text-sky-300" />Hotel planning estimates</h3><ul className="mt-2 space-y-2">{presentation.hotelEstimates.map((estimate) => <EstimateCard key={estimate.key} estimate={estimate} />)}</ul></section> : null}
    {presentation.currentCash.length > 0 ? <section aria-labelledby="exact-cash-quotes"><h3 id="exact-cash-quotes" className="flex items-center gap-2 text-sm font-medium text-slate-200">Exact cash quotes</h3><ul className="mt-2 space-y-2">{presentation.currentCash.map((quote) => <li key={quote.key} className="rounded-xl border border-white/5 bg-white/[0.02] p-3"><div className="flex flex-wrap justify-between gap-2"><span className="text-sm font-medium text-white">{quote.sourceLabel}</span><span className="text-sm font-semibold text-white">{quote.priceLabel}</span></div><p className="mt-1 text-xs text-slate-400">{quote.kind === "flight" ? "Flight" : "Hotel"} · {quote.evidenceLabel}</p>{quote.datesLabel ? <p className="mt-1 text-sm text-slate-300">{quote.datesLabel}</p> : null}<p className="mt-1 text-xs text-slate-500">{quote.coverageLabel}{quote.taxesLabel ? ` · ${quote.taxesLabel}` : ""}{quote.cancellationLabel ? ` · ${quote.cancellationLabel}` : ""}{quote.baggageLabel ? ` · ${quote.baggageLabel}` : ""}{quote.unknownCount > 0 ? ` · ${quote.unknownCount} detail${quote.unknownCount === 1 ? "" : "s"} not confirmed` : ""}</p></li>)}</ul></section> : null}
    {presentation.customerVerified.length > 0 ? <section aria-labelledby="customer-verified-options"><h3 id="customer-verified-options" className="flex items-center gap-2 text-sm font-medium text-slate-200">Customer-verified options</h3><ul className="mt-2 space-y-2">{presentation.customerVerified.map((option) => <li key={option.key} className="rounded-xl border border-white/5 bg-white/[0.02] p-3"><p className="text-sm font-medium text-white">{option.evidenceLabel}</p><p className="mt-1 text-sm text-slate-300">{option.summary}</p><p className="mt-1 text-xs text-slate-500">{option.kind === "flight" ? "Flight" : "Hotel"}{option.confirmedAtLabel ? ` · Confirmed ${option.confirmedAtLabel}` : ""}{option.unknownCount > 0 ? ` · ${option.unknownCount} detail${option.unknownCount === 1 ? "" : "s"} not confirmed` : ""}</p></li>)}</ul></section> : null}
    {presentation.alternatives.length > 0 ? <section aria-labelledby="strategic-alternatives"><h3 id="strategic-alternatives" className="flex items-center gap-2 text-sm font-medium text-slate-200"><ArrowRightLeft className="h-4 w-4 text-sky-300" />Strategic alternatives</h3><ul className="mt-2 space-y-2">{presentation.alternatives.map((alternative) => <li key={alternative.key} className="rounded-xl border border-white/5 p-3"><p className="text-sm font-medium text-white">{alternative.title}</p><p className="mt-1 text-sm text-slate-400">{alternative.tradeoff}</p></li>)}</ul></section> : null}
    <Disclosure label="Why Finance Buddy suggested this"><div className="space-y-3">{presentation.details.assumptions.length > 0 ? <div><h4 className="text-sm font-medium text-slate-200"><Lightbulb className="mr-1 inline h-4 w-4" />Planning assumptions</h4><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-slate-400">{presentation.details.assumptions.map((item, index) => <li key={`assumption-${index}`}>{item}</li>)}</ul></div> : null}{presentation.details.warnings.length > 0 ? <div><h4 className="text-sm font-medium text-amber-200"><AlertTriangle className="mr-1 inline h-4 w-4" />Important notes</h4><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-amber-100/80">{presentation.details.warnings.map((item, index) => <li key={`warning-${index}`}>{item}</li>)}</ul></div> : null}</div></Disclosure>
    {presentation.refinementTopics.length > 0 ? <Disclosure label="Fine-tune this plan"><div className="flex items-center gap-1 text-sm text-slate-400"><HelpCircle className="h-4 w-4" />Optional refinement topics</div><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-slate-400">{presentation.refinementTopics.map((item, index) => <li key={`topic-${index}`}>{item}</li>)}</ul></Disclosure> : null}
    {presentation.lastResearched && presentation.lastResearchedLabel ? <p className="border-t border-white/5 pt-3 text-xs text-slate-500">Last researched <time dateTime={presentation.lastResearched}>{presentation.lastResearchedLabel}</time> · Refresh updates your planning research. Check current availability before acting.</p> : null}
  </div>;
}
